### ISSUE TITLE
Fatal errors are not displayed

### ISSUE THREAD

**Issue by Tobion** [schmittjoh/JMSDebuggingBundle#68]
When using the debugging bundle, fatals errors of php are not displayed in development  environment anymore. Instead you just get a blank page (with xdebug) or a 500 error without any concrete info (without xdebug).

This is because the bundle registers its own [exception handler](https://github.com/schmittjoh/JMSDebuggingBundle/blob/master/Kernel/ExceptionHandler.php) that [symfony does not expect](https://github.com/symfony/symfony/blob/2.2/src/Symfony/Component/HttpKernel/Debug/ErrorHandler.php#L131) and thus won't trigger a fatal error exception.

But I'm not sure why the jms exception handler does not kick in then and handle the fatal error. I tried to make the JmsDebuggingBundle exception handler extend the HttpKernel exception handler to get recognised, but that's not so easy because the `register` methods have different signatures (static vs non-static).

**Comment by Tobion** [comment]
Closing as we don't use bundle anymore and it is outdated anyway.

**Comment by Blackskyliner** [comment]
Could you please state this in the README so people won't use it anymore?
